apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eomp.fullname" . }}-secrets
  labels:
    {{- include "eomp.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  RABBITMQ_USER: {{ .Values.secrets.rabbitmqUser | quote }}
  RABBITMQ_PASSWORD: {{ .Values.secrets.rabbitmqPassword | quote }}
  MINIO_ACCESS_KEY: {{ .Values.secrets.minioAccessKey | quote }}
  MINIO_SECRET_KEY: {{ .Values.secrets.minioSecretKey | quote }}
  GRAFANA_ADMIN_USER: {{ .Values.secrets.grafanaAdminUser | quote }}
  GRAFANA_ADMIN_PASSWORD: {{ .Values.secrets.grafanaAdminPassword | quote }}
